services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
    volumes:
      - ./setup/postgres/init:/docker-entrypoint-initdb.d
      - ./.docker/postgres:/var/lib/postgresql
    ports:
      - "5432:5432"