apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: waypoint-prod-application
  namespace: waypoint-prod
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: waypoint-prod
  project: waypoint-prod
  source:
    repoURL: ghcr.io/entigolabs/waypoint-helm
    chart: waypoint-helm
    targetRevision: 0.0.9
    helm:
      valuesObject: {}
