// This file is auto-generated by @hey-api/openapi-ts

export { getCoreCategories, getCoreEmsCategories, getCoreEmsThemes, type Options } from './sdk.gen';
export type { CategoriesResponse, Category, ClientOptions, EmsCategoriesResponse, EmsCategory, EmsTheme, EmsThemesResponse, EmsThemeTranslation, ErrorMessage, Errors, GetCoreCategoriesData, GetCoreCategoriesError, GetCoreCategoriesErrors, GetCoreCategoriesResponse, GetCoreCategoriesResponses, GetCoreEmsCategoriesData, GetCoreEmsCategoriesError, GetCoreEmsCategoriesErrors, GetCoreEmsCategoriesResponse, GetCoreEmsCategoriesResponses, GetCoreEmsThemesData, GetCoreEmsThemesError, GetCoreEmsThemesErrors, GetCoreEmsThemesResponse, GetCoreEmsThemesResponses, Metadata } from './types.gen';
