// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetCoreCategoriesData, GetCoreCategoriesErrors, GetCoreCategoriesResponses, GetCoreEmsCategoriesData, GetCoreEmsCategoriesErrors, GetCoreEmsCategoriesResponses, GetCoreEmsThemesData, GetCoreEmsThemesErrors, GetCoreEmsThemesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List categories
 */
export const getCoreCategories = <ThrowOnError extends boolean = false>(options?: Options<GetCoreCategoriesData, ThrowOnError>) => (options?.client ?? client).get<GetCoreCategoriesResponses, GetCoreCategoriesErrors, ThrowOnError>({ url: '/v1/core/categories', ...options });

/**
 * List EMS categories
 */
export const getCoreEmsCategories = <ThrowOnError extends boolean = false>(options?: Options<GetCoreEmsCategoriesData, ThrowOnError>) => (options?.client ?? client).get<GetCoreEmsCategoriesResponses, GetCoreEmsCategoriesErrors, ThrowOnError>({ url: '/v1/core/ems-categories', ...options });

/**
 * List EMS themes
 */
export const getCoreEmsThemes = <ThrowOnError extends boolean = false>(options?: Options<GetCoreEmsThemesData, ThrowOnError>) => (options?.client ?? client).get<GetCoreEmsThemesResponses, GetCoreEmsThemesErrors, ThrowOnError>({ url: '/v1/core/ems-themes', ...options });
