[database]
host = 127.0.0.1
port = 5432
database = waypoint
user = dbuser
password = password
# {{env "DB_DATASOURCE_PASSWORD"}}
version_table = sys.schema_version

[data]
apiDatasourceUser=apiuser
apiDatasourcePassword=password
# {{env "API_DATASOURCE_PASSWORD"}}
createDBTestUser=false
# test-datasource-user=testuser
# test-datasource-password={{env "TEST_DATASOURCE_PASSWORD"}}
sysRWRole=sys_rw
sysRRole=sys_r
coreRWRole=core_rw
coreRRole=core_r