backend:
  replicaCount: 2
  image: ghcr.io/entigolabs/waypoint
  tag: ""  # defaults to Chart.AppVersion
  service:
    type: ClusterIP
  port: 8081
  config:
    SERVER_ADDR: ":8081"
    ALLOWED_ORIGINS: "*"   # required, comma-separated (e.g. "https://example.com")
    API_BASE_URL: "https://andmed.eesti.ee/api"
    DB_NAME: "waypoint"
    LOG_LEVEL: "info"
    LOG_OUTPUT: "stdout"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

db:
  image: ghcr.io/entigolabs/waypoint-db
  tag: "" # defaults to Chart.AppVersion
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

frontend:
  replicaCount: 2
  image: ghcr.io/entigolabs/waypoint-front
  tag: ""  # defaults to Chart.AppVersion
  service:
    type: ClusterIP
  port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

database:
  name: "waypoint"
  releaseName: "waypoint-db"

ingress:
  className: "alb"
  host: "test.example.com"
  annotations:
    alb.ingress.kubernetes.io/group.name: "external"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
