server:
  replicaCount: 2
  image: ghcr.io/entigolabs/waypoint
  tag: ""  # defaults to Chart.AppVersion
  service:
    type: ClusterIP
    port: 8081
  config:
    port: 8081
    allowedOrigins: ""   # required, comma-separated (e.g. "https://example.com")
    apiBaseUrl: "https://andmed.eesti.ee/api"
    logLevel: "info"
    logOutput: "stdout"
    userAgent: ""
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

db:
  image: ghcr.io/entigolabs/waypoint-db
  tag: "" # defaults to Chart.AppVersion
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

database:
  name: "waypoint"
  releaseName: "waypoint-db"

ingress:
  enabled: true
  className: "alb"
  host: ""
  annotations:
    alb.ingress.kubernetes.io/group.name: "external"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
