apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccount: testbroken
      initContainers:
        - name: {{ .Release.Name }}-init
          image: "{{ .Values.db.image }}:{{ .Values.db.tag | default .Chart.AppVersion }}"
          args: [ "validate" ]
          env:
            - name: TERN_CONFIG
              value: "/tern/tern.conf"
          envFrom:
            - secretRef:
                name: {{ .Values.database.releaseName }}-{{ .Values.database.releaseName }}-user
          resources: {{ toYaml .Values.db.resources | nindent 12 }}
          volumeMounts:
            - name: tern-config-volume
              mountPath: /tern
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.releaseName | required "database.releaseName is required" }}-{{ .Release.Name }}-api-user
                  key: endpoint
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.releaseName }}-{{ .Release.Name }}-api-user
                  key: password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.releaseName }}-{{ .Release.Name }}-api-user
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.releaseName }}-{{ .Release.Name }}-api-user
                  key: username
          resources: {{ toYaml .Values.backend.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: tern-config-volume
          configMap:
            name: {{ .Release.Name }}-db-tern
