apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-front
  labels:
    app: {{ .Release.Name }}-front
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-front
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-front
    spec:
      containers:
        - name: {{ .Release.Name }}-front
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
          ports:
            - containerPort: 80
          resources: {{ toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
