apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-front
  labels:
    app: {{ .Release.Name }}-front
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-front
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-front
    spec:
      containers:
        - name: {{ .Release.Name }}-front
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
          ports:
            - containerPort: 80
          resources: {{ toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10