// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package server

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CategoriesResponse defines model for CategoriesResponse.
type CategoriesResponse struct {
	Data     []Category `json:"data"`
	Metadata Metadata   `json:"metadata"`
}

// Category defines model for Category.
type Category struct {
	Description *string  `json:"description,omitempty"`
	EmsIds      []string `json:"emsIds"`
	Id          int      `json:"id"`
	Name        string   `json:"name"`
}

// EmsCategoriesResponse defines model for EmsCategoriesResponse.
type EmsCategoriesResponse struct {
	Data     []EmsCategory `json:"data"`
	Metadata Metadata      `json:"metadata"`
}

// EmsCategory defines model for EmsCategory.
type EmsCategory struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// EmsTheme defines model for EmsTheme.
type EmsTheme struct {
	Code          string                `json:"code"`
	DatasetsCount int                   `json:"datasetsCount"`
	EmsIds        []openapi_types.UUID  `json:"emsIds"`
	Translations  []EmsThemeTranslation `json:"translations"`
}

// EmsThemeTranslation defines model for EmsThemeTranslation.
type EmsThemeTranslation struct {
	Description *string `json:"description,omitempty"`
	Language    string  `json:"language"`
	Value       string  `json:"value"`
}

// EmsThemesResponse defines model for EmsThemesResponse.
type EmsThemesResponse struct {
	Data     []EmsTheme `json:"data"`
	Metadata Metadata   `json:"metadata"`
}

// ErrorMessage defines model for ErrorMessage.
type ErrorMessage struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Errors defines model for Errors.
type Errors struct {
	Errors *[]ErrorMessage `json:"errors,omitempty"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	Total int `json:"total"`
}

// Error defines model for Error.
type Error = Errors

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List categories
	// (GET /v1/core/categories)
	GetCoreCategories(w http.ResponseWriter, r *http.Request)
	// List EMS categories
	// (GET /v1/core/ems-categories)
	GetCoreEmsCategories(w http.ResponseWriter, r *http.Request)
	// List EMS themes
	// (GET /v1/core/ems-themes)
	GetCoreEmsThemes(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List categories
// (GET /v1/core/categories)
func (_ Unimplemented) GetCoreCategories(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List EMS categories
// (GET /v1/core/ems-categories)
func (_ Unimplemented) GetCoreEmsCategories(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List EMS themes
// (GET /v1/core/ems-themes)
func (_ Unimplemented) GetCoreEmsThemes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCoreCategories operation middleware
func (siw *ServerInterfaceWrapper) GetCoreCategories(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCoreCategories(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCoreEmsCategories operation middleware
func (siw *ServerInterfaceWrapper) GetCoreEmsCategories(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCoreEmsCategories(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCoreEmsThemes operation middleware
func (siw *ServerInterfaceWrapper) GetCoreEmsThemes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCoreEmsThemes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/core/categories", wrapper.GetCoreCategories)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/core/ems-categories", wrapper.GetCoreEmsCategories)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/core/ems-themes", wrapper.GetCoreEmsThemes)
	})

	return r
}

type ErrorJSONResponse Errors

type GetCoreCategoriesRequestObject struct {
}

type GetCoreCategoriesResponseObject interface {
	VisitGetCoreCategoriesResponse(w http.ResponseWriter) error
}

type GetCoreCategories200JSONResponse CategoriesResponse

func (response GetCoreCategories200JSONResponse) VisitGetCoreCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCoreCategories500JSONResponse struct{ ErrorJSONResponse }

func (response GetCoreCategories500JSONResponse) VisitGetCoreCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCoreEmsCategoriesRequestObject struct {
}

type GetCoreEmsCategoriesResponseObject interface {
	VisitGetCoreEmsCategoriesResponse(w http.ResponseWriter) error
}

type GetCoreEmsCategories200JSONResponse EmsCategoriesResponse

func (response GetCoreEmsCategories200JSONResponse) VisitGetCoreEmsCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCoreEmsCategories500JSONResponse struct{ ErrorJSONResponse }

func (response GetCoreEmsCategories500JSONResponse) VisitGetCoreEmsCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCoreEmsThemesRequestObject struct {
}

type GetCoreEmsThemesResponseObject interface {
	VisitGetCoreEmsThemesResponse(w http.ResponseWriter) error
}

type GetCoreEmsThemes200JSONResponse EmsThemesResponse

func (response GetCoreEmsThemes200JSONResponse) VisitGetCoreEmsThemesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCoreEmsThemes500JSONResponse struct{ ErrorJSONResponse }

func (response GetCoreEmsThemes500JSONResponse) VisitGetCoreEmsThemesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List categories
	// (GET /v1/core/categories)
	GetCoreCategories(ctx context.Context, request GetCoreCategoriesRequestObject) (GetCoreCategoriesResponseObject, error)
	// List EMS categories
	// (GET /v1/core/ems-categories)
	GetCoreEmsCategories(ctx context.Context, request GetCoreEmsCategoriesRequestObject) (GetCoreEmsCategoriesResponseObject, error)
	// List EMS themes
	// (GET /v1/core/ems-themes)
	GetCoreEmsThemes(ctx context.Context, request GetCoreEmsThemesRequestObject) (GetCoreEmsThemesResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetCoreCategories operation middleware
func (sh *strictHandler) GetCoreCategories(w http.ResponseWriter, r *http.Request) {
	var request GetCoreCategoriesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCoreCategories(ctx, request.(GetCoreCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCoreCategories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCoreCategoriesResponseObject); ok {
		if err := validResponse.VisitGetCoreCategoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCoreEmsCategories operation middleware
func (sh *strictHandler) GetCoreEmsCategories(w http.ResponseWriter, r *http.Request) {
	var request GetCoreEmsCategoriesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCoreEmsCategories(ctx, request.(GetCoreEmsCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCoreEmsCategories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCoreEmsCategoriesResponseObject); ok {
		if err := validResponse.VisitGetCoreEmsCategoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCoreEmsThemes operation middleware
func (sh *strictHandler) GetCoreEmsThemes(w http.ResponseWriter, r *http.Request) {
	var request GetCoreEmsThemesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCoreEmsThemes(ctx, request.(GetCoreEmsThemesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCoreEmsThemes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCoreEmsThemesResponseObject); ok {
		if err := validResponse.VisitGetCoreEmsThemesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
