apiVersion: database.entigo.com/v1alpha1
kind: PostgreSQLDatabase
metadata:
  name: {{ .Release.Name }}
spec:
  name: {{ .Values.database | required "database is required" }}
  owner: {{ .Release.Name | replace "-" "_" }}_owner
  encoding: "UTF8"
  lcCType: "et_EE.UTF-8"
  lcCollate: "et_EE.UTF-8"
  dbTemplate: template0
  instanceRef:
    name: {{ .Release.Name }}