apiVersion: database.entigo.com/v1alpha1
kind: PostgreSQLUser
metadata:
  name: {{ .Release.Name }}-owner
spec:
  name: {{ .Release.Name | replace "-" "_" }}_owner
  instanceRef:
    name: {{ .Release.Name }}
  createDb: false
  createRole: false
  inherit: true
  login: false
---
apiVersion: database.entigo.com/v1alpha1
kind: PostgreSQLUser
metadata:
  name: {{ .Release.Name }}-user
spec:
  name: {{ .Values.dbUser | required "dbUser is required" }}
  instanceRef:
    name: {{ .Release.Name }}
  login: true
  createDb: false
  createRole: true
  inherit: true
  grant:
    roles:
      - {{ .Release.Name | replace "-" "_" }}_owner